# Site settings
title: Mabrur's Portfolio
author:
  name: Mabrur Ahmed
  email: mabrura334@gmail.com
description: My projects in computational physics and machine learning

# Build settings
remote_theme: jekyll/minima
